### ISSUE TITLE
sample robotics tasks?

### ISSUE THREAD

**Issue by DiTo97** [concept-graphs/concept-graphs#1]
Thanks for the impressive work.

I was wondering if the code for the sample robotics tasks shown in the YT video has been open-sourced in the repository.

Those tasks would be exciting to test for us, as we have a similar fleet of robots in our lab.

**Comment by DiTo97** [comment]
I will add a few more questions on the tasks as I find some points relevant with our research:
- in the CLIP vs GPT-4 querying task, you mention how GPT-4 performs better but would add a constraint in the form of the Internet connection which kinda defies the scope of an embodied AI agent, unlike CLIP. The question is what would be the cost of running such an agent with GPT-4 on all the time, which is an even bigger impediment than Internet. In this sense, 1) have you tried other LLMs for the comparison besides GPT-4? Maybe smaller and cheaper GPT variants, or local open LLMs? 2) how often has the performance of CLIP been far worse than GPT-4? In the video, there are two examples, only one of which sees GPT-4 prevail. Is there a larger benchmark of the two?
- in the traversibility puzzle which LLM have you adopted to solve the task? GPT-4, again? The video is in 1x speed, but is it showing the LLM decoding and planning as well as the Jackal robot mission execution, or just the mission execution after the planning has happened? If the former is the case, it's quite fast.

**Comment by krrish94** [comment]
@DiTo97 thanks for your interest and questions.

We haven't released the robot-specific code, mainly because of all of the ros packages and other infrastructure we built that significantly increase the dependency list and codebase complexity.

That said, we're in principle happy to share as much of the robot navigation and traversability experiment code as possible (it'd be best to reach out to @sachaMorin via email to facilitate this)!

## CLIP vs GPT-4

You are right -- the tradeoff really is that the CLIP-based system that is computationally efficient (very fast) but has limited abilities (e.g., cannot handle complex queries that don't directly address the object of interest), while the GPT-4 based system is much more capable, but assumes internet connectivity (and the inference times are between 10-30 seconds). It boils down to the kinds of tasks that you would like to do. A good first step could be to try out the CLIP-based system; and if that doesn't address your use-case, switch over to the GPT-4 based system. 

The average cost per planning query for the GPT-4 based system is US $0.2 - 0.3 (back-of-the-envelope calculation based on the scene graph we built of the [REAL lab](https://montrealrobotics.ca/)).

We tried other language models (a number of open-source LLMs including Vicuna, Llama-2; and GPT-3.5 variants), but found them all lacking (in part due to a lot of nuance in our instructions as part of the system prompt). Claude-2 from Anthropic worked well (and has a much larger context length), but we did not have API access and therefore stuck to GPT-4.

We were constantly surprised by how performant our CLIP-based system is, so chances are that you will find it helpful for a number of demos already.

## Traversability puzzle

We used GPT-4 in this too -- the exact prompt may be found in the appendix A.5. The video is only showing the mission execution after the planner has run.

**Comment by DiTo97** [comment]
Hi @krrish94,

Thank you for the prompt and super detailed response, which is not be taken for granted considering the repository is very new.

Surely, I will e-mail @sachaMorin. At our lab, we have a number of drones, delivery robots, quadrupedal robots (Spot), cobots, and rovers, and have been focusing on our VL navigation implementation building upon [VL maps](https://vlmaps.github.io/), with the add-on of multi-agente collaboration achieved through another LLM that acts as coordinator. I would gladly give your own take at the problem a try using 3D concept graphs.

In my own experience, I agree with most of your points regarding the other available LLMs. Thus far, only mosaic-7B by Mosaic ML has showed promising decoding results among the open models after a full week of benchmarking on our context and mission prompts.

**Comment by krrish94** [comment]
Closing for now; feel free to reopen if anything
