### ISSUE TITLE
TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by ibrahimyousri** [concept-graphs/concept-graphs#17]
Hi @georgegu1997  thank you for your help in my last issue!

I run The CoceptGraphs (without open-vocab detector) script successfully on RGP-D trajectories extracted from ai2thor but when runnig The ConceptGraphs-Detect  script it gives me this error 

/vol/isy-rl/GIU/ibrahim_miniconda/envs/conceptgraph/bin/python /vol/isy-rl/GIU/ibrahim/concept-graphs/conceptgraph/scripts/generate_gsa_results.py --dataset_root /vol/isy-rl/GIU/ibrahim/concept-graphs/ai2thor --dataset_config /vol/isy-rl/GIU/ibrahim/concept-graphs/conceptgraph/dataset/dataconfigs/ai2thor/ai2thor.yaml --scene_id FloorPlan4 --class_set ram --box_threshold 0.2 --text_threshold 0.2 --stride 5 --add_bg_classes --accumu_classes --exp_suffix withbg_allclasses 
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/encoder/layer/0/crossattention/self/query is tied
/encoder/layer/0/crossattention/self/key is tied
/encoder/layer/0/crossattention/self/value is tied
/encoder/layer/0/crossattention/output/dense is tied
/encoder/layer/0/crossattention/output/LayerNorm is tied
/encoder/layer/0/intermediate/dense is tied
/encoder/layer/0/output/dense is tied
/encoder/layer/0/output/LayerNorm is tied
/encoder/layer/1/crossattention/self/query is tied
/encoder/layer/1/crossattention/self/key is tied
/encoder/layer/1/crossattention/self/value is tied
/encoder/layer/1/crossattention/output/dense is tied
/encoder/layer/1/crossattention/output/LayerNorm is tied
/encoder/layer/1/intermediate/dense is tied
/encoder/layer/1/output/dense is tied
/encoder/layer/1/output/LayerNorm is tied

--------------
/vol/isy-rl/GIU/ibrahim/Grounded-Segment-Anything/Tag2Text/./ram_swin_large_14m.pth

--------------

load checkpoint from /vol/isy-rl/GIU/ibrahim/Grounded-Segment-Anything/Tag2Text/./ram_swin_large_14m.pth
vit: swin_l
msg _IncompatibleKeys(missing_keys=['visual_encoder.layers.0.blocks.0.attn.relative_position_index', 'visual_encoder.layers.0.blocks.1.attn_mask', 'visual_encoder.layers.0.blocks.1.attn.relative_position_index', 'visual_encoder.layers.1.blocks.0.attn.relative_position_index', 'visual_encoder.layers.1.blocks.1.attn_mask', 'visual_encoder.layers.1.blocks.1.attn.relative_position_index', 'visual_encoder.layers.2.blocks.0.attn.relative_position_index', 'visual_encoder.layers.2.blocks.1.attn_mask', 'visual_encoder.layers.2.blocks.1.attn.relative_position_index', 'visual_encoder.layers.2.blocks.2.attn.relative_position_index', 'visual_encoder.layers.2.blocks.3.attn_mask', 'visual_encoder.layers.2.blocks.3.attn.relative_position_index', 'visual_encoder.layers.2.blocks.4.attn.relative_position_index', 'visual_encoder.layers.2.blocks.5.attn_mask', 'visual_encoder.layers.2.blocks.5.attn.relative_position_index', 'visual_encoder.layers.2.blocks.6.attn.relative_position_index', 'visual_encoder.layers.2.blocks.7.attn_mask', 'visual_encoder.layers.2.blocks.7.attn.relative_position_index', 'visual_encoder.layers.2.blocks.8.attn.relative_position_index', 'visual_encoder.layers.2.blocks.9.attn_mask', 'visual_encoder.layers.2.blocks.9.attn.relative_position_index', 'visual_encoder.layers.2.blocks.10.attn.relative_position_index', 'visual_encoder.layers.2.blocks.11.attn_mask', 'visual_encoder.layers.2.blocks.11.attn.relative_position_index', 'visual_encoder.layers.2.blocks.12.attn.relative_position_index', 'visual_encoder.layers.2.blocks.13.attn_mask', 'visual_encoder.layers.2.blocks.13.attn.relative_position_index', 'visual_encoder.layers.2.blocks.14.attn.relative_position_index', 'visual_encoder.layers.2.blocks.15.attn_mask', 'visual_encoder.layers.2.blocks.15.attn.relative_position_index', 'visual_encoder.layers.2.blocks.16.attn.relative_position_index', 'visual_encoder.layers.2.blocks.17.attn_mask', 'visual_encoder.layers.2.blocks.17.attn.relative_position_index', 'visual_encoder.layers.3.blocks.0.attn.relative_position_index', 'visual_encoder.layers.3.blocks.1.attn.relative_position_index'], unexpected_keys=[])
ram will be used to detect classes. 
  0%|          | 0/85 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/vol/isy-rl/GIU/ibrahim/concept-graphs/conceptgraph/scripts/generate_gsa_results.py", line 635, in <module>
    main(args)
  File "/vol/isy-rl/GIU/ibrahim/concept-graphs/conceptgraph/scripts/generate_gsa_results.py", line 583, in main
    image_crops, image_feats, text_feats = compute_clip_features(
  File "/vol/isy-rl/GIU/ibrahim/concept-graphs/conceptgraph/scripts/generate_gsa_results.py", line 168, in compute_clip_features
    tokenized_text = clip_tokenizer([classes[class_id]]).to("cuda")
TypeError: list indices must be integers or slices, not NoneType

**Comment by Hoyyyaard** [comment]
@ibrahimyousri I meet the same problem. Have you already deal with it ?

**Comment by georgegu1997** [comment]
Hi @ibrahimyousri 

Thanks for your interest! 

Could you please a bit more information for debugging? Specifically, can you print the output `detections` returned by [this line](https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/scripts/generate_gsa_results.py#L551)? If you see a `None` in returned `detections.class_id`, then it might be a version difference in the GroundingDINO codebase used. Printing out `classes` at that line will also be helpful.

**Comment by Hoyyyaard** [comment]
@georgegu1997  There will be “None” class id in detections.

**Comment by ibrahimyousri** [comment]
@Hoyyyaard @georgegu1997  I used Cuda 11.7 and torch 2.0.01 and it works

**Comment by amalie-kjaer** [comment]
I am having the same issue as described above. Printing `detections` and `classes`:

CLASSES:  ['hassock', 'furniture', 'pillow', 'wall', 'dresser', 'side table', 'table', 'ceiling', 'lamp', 'floor', 'stool', 'other item', 'armchair', 'chair', 'sink', 'couch']

DETECTIONS:  Detections(xyxy=array([[7.26614990e+02, 2.41618591e+02, 1.09085132e+03, 3.91217651e+02],
       [5.79097168e+02, 5.14968872e-01, 1.19901123e+03, 3.81489258e+02],
       [7.03344238e+02, 4.88514862e+02, 9.00760986e+02, 6.73432373e+02],
       [2.33862106e+02, 2.88137329e+02, 4.09681946e+02, 4.40750977e+02],
       [4.92782593e-01, 1.62344360e+00, 5.02149353e+02, 6.77634521e+02],
       [8.27075317e+02, 4.48824615e+01, 1.04024243e+03, 2.04164703e+02],
       [3.92718506e+00, 2.97992981e+02, 1.19790381e+03, 6.78595581e+02],
       [8.15849060e+02, 2.44213669e+02, 8.59615662e+02, 2.69577393e+02],
       [7.86163208e+02, 2.19168991e+02, 8.21050537e+02, 2.65608002e+02],
       [4.01409058e+02, 1.52878052e+02, 4.41437744e+02, 1.92242523e+02],
       [1.00367334e+03, 2.18722778e+02, 1.05913965e+03, 2.88138245e+02],
       [6.70822144e+01, 5.13580383e+02, 5.09176514e+02, 6.79310364e+02],
       [2.43510223e+02, 5.82736694e+02, 4.45692230e+02, 6.79420288e+02],
       [9.61705627e+02, 5.51743958e+02, 1.19974683e+03, 6.79316589e+02],
       [4.17951050e+02, 4.94570007e+02, 5.48560730e+02, 6.01611389e+02],
       [3.14813477e+02, 4.56908752e+02, 4.68477600e+02, 5.63789734e+02]],
      dtype=float32), mask=array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       ...,

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]]), confidence=array([0.5662173 , 0.39311534, 0.3915586 , 0.3785932 , 0.3591705 ,
       0.31261092, 0.30109766, 0.29502073, 0.26154137, 0.25576878,
       0.2274856 , 0.21996579, 0.20717509, 0.20603201, 0.20465603,
       0.20034844], dtype=float32), class_id=array([None, None, 0, 8, 3, 8, 9, 11, None, 8, 0, None, 2, 0, 0, 6],
      dtype=object), tracker_id=None, data={})

`detection.class_id` does indeed return `None` for some predictions. I am using commit a4d76a2 as recommended. How could this be fixed?

Many thanks!

**Comment by alik-git** [comment]
Hi @amalie-kjaer,

Thank you for your interest in our project. Unfortunately, we don't know of an easy fix to this. As stated above, sometimes using a different cuda and pytorch version helps, but I know that causes its own problems. 

#### Temp Solution:
I have made a [commit](https://github.com/concept-graphs/concept-graphs/commit/161dc2fd8b15da48e49ebfa9174189503ab6d8b1) to just discard the detections with `class_id == None`. I have intentionally commented the code because I did not have time to test it, and I don't want to break stuff other folks. But it's very simple I just use a loop to find the `not None` indices and discard the rest.

```python
# Somehow some detections will have class_id=-None, remove them
valid_idx = [i for i, val in enumerate(detections.class_id) if val is not None]
detections.xyxy = detections.xyxy[valid_idx]
detections.confidence = detections.confidence[valid_idx]
detections.class_id = [detections.class_id[i] for i in valid_idx]         
```

#### Just to add some more context:

We are currently working on a full refactor of the code so that GroundedDINO is not needed (and many other updates as well).

However, this code is new and might break other downstream functionalities (which we will fix when we get to it, our current goal is to get it all done by May for ICRA). But you can try the new detections script [streamlined_detections.py](https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/scripts/streamlined_detections.py), and see the [readme file here](https://github.com/concept-graphs/concept-graphs/blob/ali-dev/README_streamlined_detection.md) for how to use it. We are also changing the output folder structure to make it simpler, so it might not work with other downstream code, but (for now) you can just replace the output in your current folders with the output from the new script manually. It uses YOLO-World for the detections, and the [scannet200 classes](https://github.com/concept-graphs/concept-graphs/blob/ali-dev/conceptgraph/scannet200_classes.txt) as the classes, which are held fixed. This is much simpler than the current detections pipeline. If you end up going this route, I can help you if you get stuck, I would actually appreciate the feedback on how good/bad the user experience is with the new script.

### In short, your options are:
1) Try a different pytorch / cuda version, or
2) Use this [commit](https://github.com/concept-graphs/concept-graphs/commit/161dc2fd8b15da48e49ebfa9174189503ab6d8b1) to just discard the detections that return None for the classes, or
3) Use the new [streamlined_detections.py](https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/scripts/streamlined_detections.py) script, instructions [readme file here](https://github.com/concept-graphs/concept-graphs/blob/ali-dev/README_streamlined_detection.md).


The latest code from the refactor is going to be pushed to the [ali-dev](https://github.com/concept-graphs/concept-graphs/tree/ali-dev) branch, and at some point we will deprecate the current pipeline and replace it with the "streamlined" code.

I hope that makes sense, if you have more questions let me know and I will do my best to help.

**Comment by amalie-kjaer** [comment]
Hi @alik-git, many thanks for your fast and detailed answer. For now I discarded all 'None' detections as suggested, but I will certainly try out the new detection code down the line! Will keep you in the loop about how the implementation goes. Looking forward to these updates :)
