### ISSUE TITLE
How to incremantally build the map & More info about the computation time and hardware requirement

### ISSUE THREAD

**Issue by LeeKeyu** [concept-graphs/concept-graphs#23]
Hi, thanks for your impressive contribution. I have a question regarding the code implementation. It seems that your code builds the semantic map in two separate steps - first extracting the segmentation masks and CLIP features of all the images, and second, incrementally fusing all the features. 

Is it feasible to incrementally build the map from scratch by processing one image and performing feature fusion at a time? I am also curious about the hardware setting used in the paper (especially GPU used) and the total computation time required to build a map of a room. 

Thank you in advance.

**Comment by georgegu1997** [comment]
Hi,

Thanks for your interest! Yes, our current implementation is based on three scripts that run offline for different stages of ConceptGraphs. This was mainly because SAM and GPT API had slow speeds far from real-time and we needed faster prototyping. However, it is possible to unify all scripts together into a single pipeline and actually, we are working towards a better and faster system on our end. Thanks to the recent development of faster SAM variants and dense CLIP feature extractors, I think we can get a real-time system for building object maps. 

For the hardware, we mainly used a single NVIDIA RTX3090 GPU. The segmentation and CLIP feature extraction run at 2-5s per frame (using the detector will result in fewer masks and speed up the process). The map-building process runs at ~5 FPS, depending on the number of objects in the scene. The API calling part is highly dependent on the OpenAI side. 

@alik-git Feel free to comment more on this.

**Comment by LeeKeyu** [comment]
Thank you so much for the detailed comment. This helps a lot!

**Comment by alik-git** [comment]
Hi @LeeKeyu 

It's very much in the early stages and somewhat unstable, but we are pushing the newer "streamlined" code to the [ali-dev](https://github.com/concept-graphs/concept-graphs/tree/ali-dev) branch. The incremental map building will still take a while as we are refactoring everything from scratch, but I will update here again if/when it's ready.
