### ISSUE TITLE
A request to open source subsequent experiments on robots

### ISSUE THREAD

**Issue by Xin200203** [concept-graphs/concept-graphs#26]
Great job, thanks for your hard work! May I ask whether the subsequent experimental code on the robot can be open sourced? I wanted to try to reproduce those exciting operations.

**Comment by alik-git** [comment]
Which ones specifically? The jackal or spot?

In either case, the high level design is quite straightforward and I can explain it here.

First, we generate the map of the environment using ConceptGraphs, and then the map can be queried in natural language to return the xyz location of the desired object. The code to do this is released. (And we are working on making it cleaner and nicer to use, see the ali_dev branch for now.)

For the jackal, it creates its own 3D map, which is purely geometric (i.e. no semantic information) and then this is synced to the 3D pointcloud from ConceptGraphs via the [ICP algorithm](https://en.wikipedia.org/wiki/Iterative_closest_point). Clearpath robots come with some software for this. This is so that when ConceptGraphs returns an xyz location for an object, the jackal can navigate to that xyz location in its map.

We also just have a simple check using the onboard camera of the jackal to check if the desired object is indeed present at the location returned from ConceptGraphs, we use LaVA to check that, and if its not present the given location, we again query the conceptgraphs map for an alternate location where the desired object may be present. 

Note that the ConceptGraphs map and the LLava model are running on a separate computer than that of the jackal navigation system. This is simply just because the computer onboard the jackal is not that powerful. 

Hope that helps! We may release the code for this, but at the moment it is not a priority because it will change from robot to robot and we are focusing on just making the core mapping system better for now.

**Comment by alik-git** [comment]
@sachaMorin also worked on the real robot experiments, he may have some more thoughts on this.

**Comment by alik-git** [comment]
If you have more questions, feel free to ask and I will do my best to help.

**Comment by sachaMorin** [comment]
Happy to share the Jackal code, I'll do so later this week. I'm not the owner of the Spot code but iirc this one cannot be open sourced.

**Comment by sachaMorin** [comment]
Shared the code [here](https://github.com/sachaMorin/concept_graphs_jackal). It's quite rough around the edges, but I hope it will prove useful!

**Comment by ayushzenith** [comment]
Hi! Is there someone who has the spot code/could I contact anybody for access/to open source the spot code?

**Comment by georgegu1997** [comment]
Hi @ayushzenith, our collaborators at JHU handled the spot robot experiments. Recently they released a newer paper called [ConceptAgent](https://arxiv.org/abs/2410.06108) with several improvements in planning and manipulation. Feel free to contact them for details.
