### ISSUE TITLE
Depth map using Marigold, Depth-Anything

### ISSUE THREAD

**Issue by HennethAnnun** [concept-graphs/concept-graphs#41]
Hi Ali, I am testing your algorithm using the Replica/room0 dataset. I decided to test the depth map algorithm by Marigold: https://github.com/prs-eth/Marigold
I have replaced Replica depth maps with those from Marigold. Here is an example:

Replica depth map:
![depth000000_oryginal_Replica](https://github.com/concept-graphs/concept-graphs/assets/26388511/3416db59-cb74-4962-875a-c8e4d38f34c1)

Marigold depth map:
![depth000000_marigold_best](https://github.com/concept-graphs/concept-graphs/assets/26388511/2f485b5b-64d5-48b4-a4fd-534161994765)

My issue is, while running rerun_realtime_mapping.py I get a lot of detections. They seem not to get merged. The map gets bloated.
Could you hint me if the depth map is OK and what am I doing wrong?
I can generate the whole depth map for room0 and share, if you need this for your own testing.

**Comment by HennethAnnun** [comment]
Here is a depth map from Depth-Anything: https://github.com/LiheYoung/Depth-Anything
Faster model, results not good.

Depth-Anything map:
![depth000000_depthanything](https://github.com/concept-graphs/concept-graphs/assets/26388511/b36ab504-06ef-4cff-8a50-8671154a6c13)

**Comment by alik-git** [comment]
Hi @HennethAnnun,

Thanks for using ConceptGraphs!

Just so I understand you correctly, have you tried running the code with the ground truth depth and it works fine? As in, you're sure that it is the estimated depth map that is causing the problem?

I agree that the depth map looks fine upon first glance.

**Comment by HennethAnnun** [comment]
Yes, the ground truth depth map from Replica works fine. I would like to
use some other, compatible, algorithm for depth maps. Did you try any
other? Maybe you could point me to some direction?


Pozdrawiam / Best Regards / MfG

Marek Kroplewski

--- sent from mobile

wt., 28 maj 2024, 21:47 użytkownik Ali Kuwajerwala ***@***.***>
napisał:

**Comment by krrish94** [comment]
Chiming in for a quick resolution here.

### The actual issue

The depth maps predicted by these models are off by a global scale factor with respect to the real-world. i.e., the "relative" depths may all look sensible, while the "absolute" depth values (think units of "metres") are off by a scale factor, which is not known ahead of time. Further, this scale factor potentially changes for every image the network is run on.

Given this scale offset, the camera poses you have from replica ground truth are rendered incorrect (the translations in the pose matrix are off by the same scale factor, which needs to be estimated). If you're determined to make this approach work, you will need to implement your custom pose estimation framework that provides relative poses (and also scale the depth maps accordingly).

### The fix

There unfortunately is no easy fix you can use off-the-shelf in this case. Perhaps newer approaches like [dust3r](https://github.com/naver/dust3r) can predict consistent depths/pointclouds. Then again, life will be much easier if you assume access to and use depthmaps.

(Closing this issue for now, since this isn't something we plan to support anytime soon)
