### ISSUE TITLE
Codes and instructions of AI2Thor experiments

### ISSUE THREAD

**Issue by mohan-li** [concept-graphs/concept-graphs#62]
Hi, could you please advise where to access the codes and instructions to conduct AI2Thor experiments? Thanks a lot!

**Comment by georgegu1997** [comment]
Thanks for your interest!

Please find instructions on how to generate RGB-D sequences using AI2Thor [here](https://github.com/concept-graphs/concept-graphs?tab=readme-ov-file#generating-ai2thor-datasets). After generating the sequence, you can run the main script to build a scene graph for the AI2Thor simulation environment. 

We don't plan to release the code for localization experiments on AI2Thor, since it was mostly a prototype for the simulation environment and it does not extend to the real world or any other meaningful settings without non-trivial modifications. Localization is also not the major contributions of ConceptGraphs. (some code has been released in #55 though)

Closing this issue for now. Feel free to re-open if you have follow-up questions.
